apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  type: NodePort
  selector:
    name: mongodb-stateful
  ports:
    - port: 27017
      targetPort: 27017
      nodePort: 30002

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb-stateful
  labels:
    name: mongodb-stateful
spec:
  # https://github.com/kubernetes/kubernetes/issues/69608
  serviceName: mongodb-stateful-service
  replicas: 1
  selector:
    matchLabels:
      name: mongodb-stateful
  volumeClaimTemplates:
    - metadata:
        name: mongodb-pvc
      spec:
        accessModes:
          - ReadWriteOnce
        volumeMode: Filesystem
        resources:
          requests:
            storage: 20Gi
  template:
    metadata:
      name: mongodb-stateful
      labels:
        name: mongodb-stateful
    spec:
      containers:
        - name: mongodb-stateful
          image: mongo:latest
          ports:
          - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username

            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password

          volumeMounts:
            - mountPath: /data/db
              name: mongodb-pvc